// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQJq7m224ZXNjtM1ddWMxKDXpYT-cbtC4',
    appId: '1:875736169748:web:abfcfeb036d98f2e639601',
    messagingSenderId: '875736169748',
    projectId: 'fir-app-d986a',
    authDomain: 'fir-app-d986a.firebaseapp.com',
    storageBucket: 'fir-app-d986a.appspot.com',
    measurementId: 'G-TX9EZ6W95T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCadtZk2fJ2CyJU3OgG8r2VsZBfLDIBvDE',
    appId: '1:875736169748:android:c1ad61dde7774079639601',
    messagingSenderId: '875736169748',
    projectId: 'fir-app-d986a',
    storageBucket: 'fir-app-d986a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNdrtuIAF5tAgqG6Jwrd4d0ac1y8S2HM',
    appId: '1:875736169748:ios:54991237929e7f18639601',
    messagingSenderId: '875736169748',
    projectId: 'fir-app-d986a',
    storageBucket: 'fir-app-d986a.appspot.com',
    androidClientId: '875736169748-fjcbfg8npa837k0e98sum9h9pfc9rrs4.apps.googleusercontent.com',
    iosClientId: '875736169748-hdlv0qag5as0duadej7kv06md5nna0pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapptwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTNdrtuIAF5tAgqG6Jwrd4d0ac1y8S2HM',
    appId: '1:875736169748:ios:da4fd8761fe2ca48639601',
    messagingSenderId: '875736169748',
    projectId: 'fir-app-d986a',
    storageBucket: 'fir-app-d986a.appspot.com',
    androidClientId: '875736169748-fjcbfg8npa837k0e98sum9h9pfc9rrs4.apps.googleusercontent.com',
    iosClientId: '875736169748-jb157v4j941283oo3s2fjb3k5i9etsuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapptwo.RunnerTests',
  );
}
